config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #devise_for :users, :controllers => { application: 'application' }
  #root 'home#index'
  
  root "attempts#new"
  
  resources :questions do
    resources :answers
  end
  resources :attempts


end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :user
    belongs_to :question
    before_save :correct_answer
    validates :answer, inclusion: {in: [true, false], message: 'is not a valid answer!'}
   
    def correct_answer
      self.correct = (question.correct_answer == answer)
      true
    end
  
    def self.difficulty(hard_level = true)
      answers = (hard_level ? 'false': 'true')
      self.find_by_sql('SELECT COUNT(answers.correct) AS stats, answers.question_id FROM answers WHERE correct = '+answers+' GROUP BY question_id ORDER BY stats DESC LIMIT 1')
    end
  
    def self.user_correct_per(user)
      user_all_answers = Answer.user_answers(user)
      user_correct_answers = Answer.user_correct_answers(user)
      (user_correct_answers.to_i*100)/(user_all_answers.to_i)
    end
  
     def self.user_answers(user)
      user_all_answers = Answer.where('user_id = ? ', user[:user_id]).count
      user_all_answers.to_s === '0' ? 1 :  user_all_answers.to_s
    end
  
    def self.user_correct_answers(user)
      Answer.where('user_id = ? AND correct = true', user[:user_id]).order(:question_id).count.to_s
    end
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attempt.rb
class Attempt < ApplicationRecord
    def self.statistic_users
        users_quiz = format_user_stat
        update_scores(users_quiz)
      end
    
      def self.statistic_questions
        quiz = {}
        quiz[:users_all] = User.all.count
        quiz[:questions_all] = Question.all.count
        quiz[:hardest_question] = Question.hardest_question
        quiz[:easiest_question] = Question.easiest_question
        return quiz
      end
    
      def self.format_user_stat
        users_quiz = []
        User.all.each{|user|
           users_quiz << {:email => user.email, :score => 0, user_id: user.id}
        }
        users_quiz
      end
    
      def self.update_scores(users_quiz)
        users_quiz.map{|user|
          user[:score] = Answer.user_correct_per(user).to_i
        }
        users_quiz
      end
    
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :user
    has_many :answer
    validates :description, presence: true, length: { minimum: 5 }, uniqueness: true
      
      def self.start_the_quiz(user)
            random_question = Question.find_by_sql ['Select * from questions where questions.user_id <> ? AND questions.id NOT IN (SELECT DISTINCT question_id from answers where user_id = ?) ORDER BY RANDOM() ', user.id, user.id]
            return random_question.first   
      end
  
    def self.hardest_question
      hard = Answer.difficulty
      return 'None' if hard.empty?
      hard_desc = Question.select('description').where('id = ?',hard[0].question_id)
      h_score = hard_desc[0]['description'].to_s
      return h_score
    end
  
    def self.easiest_question
      easy = Answer.difficulty(false)
      return 'None' if easy.empty?
      easy_desc = Question.select('description').where('id = ?',easy[0].question_id)
      e_score = easy_desc[0]['description'].to_s
      return e_score
    end


  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions
  has_many :answers
  
  # before_commit :is_admin?

  # def index

  # end

  # def is_admin?
  #   redirect_to root_path if !current_user.admin?
  # end

  def username
    return self.email.split('@')[0].capitalize
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    before_action :authenticate_user!

	def create
		@question = Question.find params[:question_id]
		@answer = Answer.new(params[:answer].permit(:answer))
		@answer.question_id = @question.id
		@answer.user = current_user
    if @answer.save!
     	@answer.correct ? flash[:success] = "Correct Answer!" : flash[:error] = "Incorrect Answer!"
			redirect_to  new_attempt_path
		else
			redirect_to questions_path
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :admin) } # The :firstname and :lastname are my custom fields.
  end
  
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
    def show
        redirect_to new_attempt_path
        #redirect_to  new_user_session_path
    end

    def new
        @random_question = Question.start_the_quiz(current_user)
        @answer = Answer.new(question: @random_question, user: current_user)

        unless @random_question
            set_flash_msg
            #redirect_to  new_user_session_path
            redirect_to questions_path
        end
    end

    def index
        @quiz = Attempt.statistic_questions
        @users_quiz = Attempt.statistic_users
        render 'index'
    end	

protected

    def set_flash_msg
      flash[:success] = flash[:success]
      flash[:error] = flash[:error]
      flash[:notice] = " You answered all the questions or no questions in quiz!"
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

    def new
        @question = Question.new
      end
    
      def create
        @question = Question.new params[:question].permit(:description, :correct_answer)
        @question.user = current_user
        if @question.save
          redirect_to questions_path
        else
          render 'new'
        end
      end
     
      def show
        @question = Question.find params[:id] 
      end
    
      def quiz
        @questions = Question.where("user_id <> ?", current_user)
        @question = @questions[0]

      end
    
      def index
        @questions = Question.where("user_id = ?", current_user)
      end
    
      def edit
        @question = Question.find params[:id]
      end
    
      def update
        @question = Question.find params[:id]
        @question.update params[:question].permit(:description, :correct_answer)
        redirect_to questions_path
      end
    
      def destroy
        @question = Question.find params[:id]
        @question.destroy
        redirect_to questions_path
      end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attempts_helper.rb
module AttemptsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/attempts/index.html.erb
<h1> Quiz statistic! </h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>All users</th>
      <th>All questions</th>
      <th>Hardest Q</th>
      <th>Easiest Q</th>

    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= @quiz[:users_all] %></td>
        <td><%= @quiz[:questions_all] %></td>
        <td><%= @quiz[:hardest_question] %></td>
        <td><%= @quiz[:easiest_question] %></td>
       
      </tr>
    
  </tbody>

</table>
<div class='row'>
  <% @users_quiz.each do |user| %>
    <div class='col-sm-3 alert <%=  %>'>
      <h4>User's <%= user[:email] %> scores:</h4>
     Correct: <%= user[:score]  %>%, Incorrect:<%= 100 - user[:score]  %>% <br />
    </div>
  <% end %>
</div>

app/views/attempts/new.html.erb
<% $name = current_user.present? ? current_user.username : 'Stranger' %>

<h1>Welcome, <%= $name %> </h1>
<div class='row single-question centered'>


<% if @answer.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this post from being saved:</h2>
 
    <ul>
    <% @answer.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [@random_question, @answer] do |form| %>
<div class="question-description">
  <%= @random_question.description %>?
</div>
<div class="question-answer">
  <span class="correct">
  <%= form.label :answer, 'Correct?' %>
  <%= form.radio_button :answer, true  %>
</span>
<span class="incorrect">
  <%= form.label :answer, 'Incorrect?' %>
  <%= form.radio_button :answer, false %>
</span>
</div>
<div class="controls-buttons">
  <%= form.hidden_field :question_id %>
  <%= form.button 'Next Question', :class => 'btn btn-primary' %>
</div>
  
<% end %>
</div>

app/views/home/index.html.erb
<% $name = current_user.present? ? current_user.username : 'Stranger' %>

<h1>Welcome, <%= $name %> </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestRailsQuiz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'shared/navbar' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <% if user_signed_in? %>
                <li>
                <%= link_to('Quiz', '/')  %>
                </li>
                <li>
                <%= link_to('Questions', questions_path)  %>
                </li>
                 <li>
                <%= link_to('Statistic', '/attempts')  %>
                </li>
                 <li>
                <%= link_to('Edit profile', edit_user_registration_path) %>
                </li>
                <li>
                 <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
                </li>
              <% else %>
              <li>
                <%= link_to('Login', new_user_session_path)  %>  
                </li>
                <li>
                <%= link_to('Register', new_user_registration_path)  %>
                </li>
              <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<% $name = current_user.present? ? current_user.username : 'Stranger' %>

<h1>Welcome, <%= $name %> </h1>

app/views/questions/_form.html.erb
<% if @question.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@question.errors.count, "error") %> prohibited this post from being saved:</h2>
 
    <ul>
    <% @question.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class='row single-question'>
<%= form_for @question, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :description,  'Question Description', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
  <%= f.radio_button :correct_answer, false %>
  <%= f.label :correct_answer, "Incorrect" %>
 
  </div>
  <div class="control-group">
   <%= f.radio_button :correct_answer, true %>  
  <%= f.label :correct_answer, "Correct" %>
   
  </div>

  <hr />
  <div class="controls-buttons">
  <%= f.button nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            questions_path, :class => 'btn btn-default' %>
 </div>
<% end %>
</div>

app/views/questions/edit.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/questions/index.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:correct_answer) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% if @questions.none? %>
      <tr>
        <td colspan='6'> No Questions yet!</td>
      </tr>
    <% else %>
    <% @questions.each do |question| %>
      <tr>
        <td><%= link_to question.id, question_path(question) %></td>
        <td><%= truncate question.description, length: 140 %></td>
        <td><%= question.user.email %></td>
        <td><%= question.correct_answer %></td>
        <td> Created <%= time_ago_in_words question.created_at %> ago</td>
        <td>
          <%= link_to :Show, question_path(question), :class => 'btn btn-default btn-xs'  %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_question_path(question), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      question_path(question),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
    <% end %>
  </tbody>

</table>
<p>

</p>
<div class="controls-buttons">

<% if current_user.admin? %>
  <%= link_to t('.new', :default => t("helpers.links.new")), new_question_path, :class => 'btn btn-primary' %>
<% end %>


</div>

app/views/questions/new.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/questions/show.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<div class="row single-question">
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @question.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:correct_answer) %>:</strong></dt>
  <dd><%= @question.correct_answer %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @question.user.email %></dd>
 
</dl>

<hr/>
    <div class="controls-buttons">
    <%= link_to t('.back', :default => t("helpers.links.back")),
                  questions_path, :class => 'btn btn-default'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_question_path(@question), :class => 'btn btn-default' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  question_path(@question),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger' %>
    </div>
</div>
<hr />
<% if !@question.answer.none? %>
<%- model_class = Answer -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<div class='row'>
  <% @question.answer.each do |answer| %>
    <div class='col-sm-3 alert_<%=  answer.answer == @question.correct_answer ? 'correct' : 'incorrect' %>'>
      <h4>User's <%= answer.user.email %> answer:</h4>
      <%= answer.answer %> - <%=  answer.answer == @question.correct_answer ? 'which is Correct' : ' which is Wrong' %><br />
       <%= answer.created_at %>
    </div>
  <% end %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">TestTask</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

  </div>
</nav>